export {default as HeroSection} from "./Hero"
export {default as Navigation} from "./Navigation"
export {default as Products} from "./Products"
export {default as Location} from "./Location"
export {default as About} from "./About"
export {default as Contacts} from "./Contacts"